#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function getCurrentBranch() {
  try {
    return execSync('git rev-parse --abbrev-ref HEAD', {
      encoding: 'utf-8',
    }).trim();
  } catch {
    console.warn('Warning: Could not get git branch, using "unknown"');
    return 'unknown';
  }
}

function getBuildInfoPath(branch = getCurrentBranch()) {
  return path.join(process.cwd(), `buildinfo-${branch}.json`);
}

function getBuildConfigPath() {
  return path.join(process.cwd(), 'src', 'config', 'buildinfo-generated.ts');
}

function readBuildInfo(branch = getCurrentBranch()) {
  const buildInfoPath = getBuildInfoPath(branch);
  const defaults = {
    buildNumber: 0,
    versionCode: 0,
    versionName: branch === 'main' ? '0.1.0' : '0.0.1',
    lastBuildDate: new Date().toISOString(),
  };

  if (!fs.existsSync(buildInfoPath)) {
    return defaults;
  }

  try {
    return JSON.parse(fs.readFileSync(buildInfoPath, 'utf-8'));
  } catch {
    console.warn(`Warning: Could not parse ${buildInfoPath}, using defaults`);
    return defaults;
  }
}

function writeBuildInfoTs(buildInfo, branch = getCurrentBranch()) {
  const buildConfigPath = getBuildConfigPath();
  const buildNumber = buildInfo.buildNumber ?? 0;
  const buildDate = new Date(buildInfo.lastBuildDate).toLocaleDateString();
  const formattedBuild = `Build #${buildNumber} (${branch}) - ${buildDate}`;

  const buildConfigContent = `/**
 * AUTOGENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/increment-build.cjs during build process
 */

export interface BuildInfo {
  buildNumber: number;
  branchName: string;
  buildDate: string;
  formattedBuild: string;
}

export const buildInfo: BuildInfo = {
  buildNumber: ${buildNumber},
  branchName: '${branch}',
  buildDate: '${buildDate}',
  formattedBuild: '${formattedBuild.replace(/'/g, "\\'")}',
};

export function formatBuildNumber(): string {
  return buildInfo.formattedBuild;
}

export function getBuildInfo(): BuildInfo {
  return buildInfo;
}
`;

  fs.mkdirSync(path.dirname(buildConfigPath), { recursive: true });
  fs.writeFileSync(buildConfigPath, buildConfigContent);
}

module.exports = {
  getCurrentBranch,
  getBuildInfoPath,
  getBuildConfigPath,
  readBuildInfo,
  writeBuildInfoTs,
};
