#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

let currentBranch = 'unknown';
try {
  currentBranch = execSync('git rev-parse --abbrev-ref HEAD', {
    encoding: 'utf-8',
  }).trim();
} catch {
  console.warn('Warning: Could not get git branch, using "unknown"');
}

const buildInfoPath = path.join(process.cwd(), `buildinfo-${currentBranch}.json`);
const buildConfigPath = path.join(
  process.cwd(),
  'src',
  'config',
  'buildinfo-generated.ts'
);

let buildInfo = {
  buildNumber: currentBranch === 'main' ? 0 : 0,
  versionCode: currentBranch === 'main' ? 0 : 0,
  versionName: currentBranch === 'main' ? '0.1.0' : '0.0.1',
  lastBuildDate: new Date().toISOString(),
};

if (fs.existsSync(buildInfoPath)) {
  try {
    buildInfo = JSON.parse(fs.readFileSync(buildInfoPath, 'utf-8'));
  } catch {
    console.warn(`Warning: Could not parse ${buildInfoPath}, using defaults`);
  }
} else {
  console.log(`Creating ${buildInfoPath} with defaults for ${currentBranch}`);
}

buildInfo.buildNumber++;
buildInfo.versionCode++;
buildInfo.lastBuildDate = new Date().toISOString();

fs.mkdirSync(path.dirname(buildConfigPath), { recursive: true });
fs.writeFileSync(buildInfoPath, JSON.stringify(buildInfo, null, 2));

const newBuildNumber = buildInfo.buildNumber;
const buildDate = new Date(buildInfo.lastBuildDate).toLocaleDateString();
const formattedBuild = `Build #${newBuildNumber} (${currentBranch}) - ${buildDate}`;

const buildConfigContent = `/**
 * AUTOGENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/increment-build.cjs during build process
 */

export interface BuildInfo {
  buildNumber: number;
  branchName: string;
  buildDate: string;
  formattedBuild: string;
}

export const buildInfo: BuildInfo = {
  buildNumber: ${newBuildNumber},
  branchName: '${currentBranch}',
  buildDate: '${buildDate}',
  formattedBuild: '${formattedBuild.replace(/'/g, "\\'")}',
};

export function formatBuildNumber(): string {
  return buildInfo.formattedBuild;
}

export function getBuildInfo(): BuildInfo {
  return buildInfo;
}
`;

fs.writeFileSync(buildConfigPath, buildConfigContent);
console.log(`✓ ${formattedBuild}`);
